### ISSUE TITLE
Site analytics

### ISSUE THREAD

**Issue by MBrouns** [PyDataAmsterdam/amsterdam.pydata.org#12]
It could be nice to have an idea of how many visitors we have and what parts of the site they're visiting. 

The obvious option here is google analytics but maybe someone has another suggestion. I know @koaning is happy about https://plausible.io/ but it seems to be more suitable for a single person multiple website situation, whereas we have it the other way around. 

Any other suggestions or should we just go with GA.

**Comment by Nelson-AM** [comment]
I would strongly prefer to stay away from GA as I don't want to facilitate exposing our visitors' data to them. GA also seems like overkill for the data we might want to collect.

What statistics are we interested in?

- Hits on (parts of the) site. Would we want to know the number of unique visitors or just the number of visits?

**Comment by MBrouns** [comment]
I also don't particularly like google analytics but it does seem to be what NumFocus uses on the general PyData site. 

in terms of statistics I think the following would be interesting:
- unique visitors
- total pageviews and per page
- conversions to eventbrite / sponsor prospectus etc
- referrers
- source urls
- behaviour flow
- geographic location

**Comment by MBrouns** [comment]
How about this one: https://www.goatcounter.com/
