### ISSUE TITLE
Need to add (a) page(s) about meetups

### ISSUE THREAD

**Issue by Nelson-AM** [PyDataAmsterdam/amsterdam.pydata.org#3]

**Comment by MBrouns** [comment]
Good one!  Might be nicest if we could somehow get the feed from meetup.com and display it on a page rather than us needing to update the site every time?

**Comment by JCZuurmond** [comment]
I do agree it would be nice to automate that. On the other hand it might be premature optimisation(?).

I do not know how easy it is to access the feed.

**Comment by MBrouns** [comment]
You're probably right, let's add them manually for now.

**Comment by clamm** [comment]
<img width="321" alt="Screenshot 2020-02-19 at 19 16 33" src="https://user-images.githubusercontent.com/2931028/74862472-827be900-534c-11ea-9dd9-33493751754f.png">

The date of the past meetup that is added as a start (I guess?) is wrong. It shows 26 Feb 2019 when it should be 11 December 2019. I think it takes the date from the file name in the posts/_meetups folder so I can easily fix this.
